[package]
name = "crypto"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10"
generic-array = "1"
json = "0.12.4"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0"